# Generated by Django 5.0.2 on 2024-02-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First_qr_code_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=200)),
                ('field1', models.CharField(max_length=200)),
                ('value1', models.CharField(max_length=200)),
                ('field2', models.CharField(max_length=200)),
                ('value2', models.CharField(max_length=200)),
                ('field3', models.CharField(max_length=200)),
                ('value3', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'first_qr_code_table',
            },
        ),
    ]
